// Auto-generated by LibreLane
module aes_core_256(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input reset_n,
  input key_load,
  input[255:0] key_in,
  output key_ready,
  input start,
  input mode,
  input[127:0] din,
  output[127:0] dout,
  output ready,
  output done
);
endmodule
